# Generated by Django 4.2.28 on 2026-02-14 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devotee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('nakshatra', models.CharField(choices=[('Aswathy', 'Aswathy'), ('Bharani', 'Bharani'), ('Karthika', 'Karthika'), ('Rohini', 'Rohini'), ('Makayiram', 'Makayiram'), ('Thiruvathira', 'Thiruvathira'), ('Punartham', 'Punartham'), ('Pooyam', 'Pooyam'), ('Ayilyam', 'Ayilyam'), ('Makam', 'Makam'), ('Pooram', 'Pooram'), ('Uthram', 'Uthram'), ('Atham', 'Atham'), ('Chithria', 'Chithria'), ('Chothi', 'Chothi'), ('Vishakham', 'Vishakham'), ('Anizham', 'Anizham'), ('Thrikketta', 'Thrikketta'), ('Moolam', 'Moolam'), ('Pooradam', 'Pooradam'), ('Uthradam', 'Uthradam'), ('Thiruvonam', 'Thiruvonam'), ('Avittam', 'Avittam'), ('Chathayam', 'Chathayam'), ('Pooruruttathi', 'Pooruruttathi'), ('Uthruttathi', 'Uthruttathi'), ('Revathi', 'Revathi')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='devotee',
            constraint=models.UniqueConstraint(fields=('name', 'country_code', 'phone'), name='unique_devotee'),
        ),
    ]
