# Generated by Django 4.2.28 on 2026-02-19 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devotees', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devotee',
            options={'ordering': ['-created_at'], 'verbose_name': 'Devotee', 'verbose_name_plural': 'Devotees'},
        ),
        migrations.RemoveConstraint(
            model_name='devotee',
            name='unique_devotee',
        ),
        migrations.AlterField(
            model_name='devotee',
            name='country_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='devotee',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='devotee',
            name='nakshatra',
            field=models.CharField(choices=[('ASWATHY', 'ASWATHY'), ('BHARANI', 'BHARANI'), ('KARTHIKA', 'KARTHIKA'), ('ROHINI', 'ROHINI'), ('MAKAYIRAM', 'MAKAYIRAM'), ('THIRUVATHIRA', 'THIRUVATHIRA'), ('PUNARTHAM', 'PUNARTHAM'), ('POOYAM', 'POOYAM'), ('AYILYAM', 'AYILYAM'), ('MAKAM', 'MAKAM'), ('POORAM', 'POORAM'), ('UTHRAM', 'UTHRAM'), ('ATHAM', 'ATHAM'), ('CHITHRIA', 'CHITHRIA'), ('CHOTHI', 'CHOTHI'), ('VISHAKHAM', 'VISHAKHAM'), ('ANIZHAM', 'ANIZHAM'), ('THRIKKETTA', 'THRIKKETTA'), ('MOOLAM', 'MOOLAM'), ('POORADAM', 'POORADAM'), ('UTHRADAM', 'UTHRADAM'), ('THIRUVONAM', 'THIRUVONAM'), ('AVITTAM', 'AVITTAM'), ('CHATHAYAM', 'CHATHAYAM'), ('POORURUTTATHI', 'POORURUTTATHI'), ('UTHRUTTATHI', 'UTHRUTTATHI'), ('REVATHI', 'REVATHI')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='devotee',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='devotee',
            name='phone',
            field=models.CharField(db_index=True, max_length=15),
        ),
        migrations.AddIndex(
            model_name='devotee',
            index=models.Index(fields=['name', 'phone'], name='devotees_de_name_a6dc20_idx'),
        ),
        migrations.AddIndex(
            model_name='devotee',
            index=models.Index(fields=['nakshatra', 'created_at'], name='devotees_de_nakshat_afcb61_idx'),
        ),
        migrations.AddConstraint(
            model_name='devotee',
            constraint=models.UniqueConstraint(fields=('name', 'country_code', 'phone', 'nakshatra'), name='unique_devotee_per_nakshatra'),
        ),
    ]
