# Generated by Django 4.2.28 on 2026-02-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devotees', '0002_alter_devotee_options_remove_devotee_unique_devotee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DuplicateEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=15)),
                ('nakshatra', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Duplicate Entry',
                'verbose_name_plural': 'Duplicate Entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvalidEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('country_code', models.CharField(blank=True, max_length=10)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('nakshatra', models.CharField(blank=True, max_length=50)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Invalid Entry',
                'verbose_name_plural': 'Invalid Entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
