# Generated by Django 4.2.28 on 2026-02-20 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devotees', '0003_duplicateentry_invalidentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devotee',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='duplicateentry',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='invalidentry',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='devotee',
            name='nakshatra',
            field=models.CharField(choices=[('ASWATHY', 'ASWATHY'), ('BHARANI', 'BHARANI'), ('KARTHIKA', 'KARTHIKA'), ('ROHINI', 'ROHINI'), ('MAKAYIRAM', 'MAKAYIRAM'), ('THIRUVATHIRA', 'THIRUVATHIRA'), ('PUNARTHAM', 'PUNARTHAM'), ('POOYAM', 'POOYAM'), ('AYILYAM', 'AYILYAM'), ('MAKAM', 'MAKAM'), ('POORAM', 'POORAM'), ('UTHRAM', 'UTHRAM'), ('ATHAM', 'ATHAM'), ('CHITHIRA', 'CHITHIRA'), ('CHOTHI', 'CHOTHI'), ('VISHAKHAM', 'VISHAKHAM'), ('ANIZHAM', 'ANIZHAM'), ('THRIKKETTA', 'THRIKKETTA'), ('MOOLAM', 'MOOLAM'), ('POORADAM', 'POORADAM'), ('UTHRADAM', 'UTHRADAM'), ('THIRUVONAM', 'THIRUVONAM'), ('AVITTAM', 'AVITTAM'), ('CHATHAYAM', 'CHATHAYAM'), ('POORURUTTATHI', 'POORURUTTATHI'), ('UTHRUTTATHI', 'UTHRUTTATHI'), ('REVATHI', 'REVATHI')], db_index=True, max_length=50),
        ),
    ]
